"""Export the public Pydantic web contracts as TypeScript (stdout, no secrets).

Run with the installed controller interpreter: python -I tools/export_web_types.py.
The small converter fails closed for unsupported schema shapes; the frontend must
not hand-maintain a second interpretation of controller response structures.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from firstrun.domain import web, web_session


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"integer", "number"}:
        return "number"
    if kind == "array":
        return f"ReadonlyArray<{ts_type(schema['items'])}>"
    if kind == "object":
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        # Pydantic response defaults are present in JSON; request defaults alone
        # are optional. All current request fields are required.
        fields = [f"  readonly {json.dumps(key)}{'?' if key not in required and 'default' not in value else ''}: {ts_type(value)};"
                  for key, value in properties.items()]
        return "{\n" + "\n".join(fields) + "\n}"
    raise ValueError(f"Unsupported public schema shape: {kind}")


def render() -> str:
    definitions = {}
    for name, model in [(name, getattr(module, name))
                        for module in (web, web_session) for name in module.__all__]:
        schema = model.model_json_schema(mode="serialization")
        definitions.update(schema.pop("$defs", {}))
        definitions[name] = schema
    header = "// Generated by tools/export_web_types.py from firstrun.domain.web. Do not edit.\n\n"
    return header + "\n\n".join(f"export type {name} = {ts_type(schema)};"
                                  for name, schema in sorted(definitions.items())) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    content = render()
    if args.check:
        if not args.check.is_file() or args.check.read_text(encoding="utf-8") != content:
            raise SystemExit("Generated web types are out of date")
        print("Public web types match Pydantic contracts")
    else:
        print(content, end="")
