// Generated by tools/export_web_types.py from firstrun.domain.web. Do not edit.

export type BaselineView = {
  readonly "tested_sha": string;
  readonly "outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed";
  readonly "commands": ReadonlyArray<CommandView>;
  readonly "readiness_outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed" | null;
  readonly "functional_outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed" | null;
  readonly "target_digest": string;
  readonly "recipe_digest": string;
  readonly "verifier_digest": string;
  readonly "runtime_image_id": string;
  readonly "cleanup_succeeded": boolean;
};

export type CandidateDiffView = {
  readonly "patch_digest": string;
  readonly "candidate_tree_digest": string;
  readonly "paths": ReadonlyArray<".firstrun/recipe.json" | "README.md">;
  readonly "unified_diff": string;
};

export type CaseDetail = {
  readonly "case": CaseSummary;
  readonly "message": string;
  readonly "baseline": BaselineView | null;
  readonly "proof": ProofView | null;
  readonly "exact_commit_proof": ProofView | null;
  readonly "candidate": CandidateDiffView | null;
  readonly "needs_input": NeedsInputView | null;
  readonly "events": EventPage;
  readonly "repair_pr_number": number | null;
  readonly "repair_pr_url": string | null;
  readonly "check_url": string | null;
};

export type CasePage = {
  readonly "items": ReadonlyArray<CaseSummary>;
  readonly "next_cursor": string | null;
};

export type CaseSummary = {
  readonly "id": string;
  readonly "repository_id": number;
  readonly "sha": string;
  readonly "phase": "queued" | "fetching" | "baseline_running" | "investigating" | "needs_input" | "proof_running" | "verified" | "repair_ready" | "publishing" | "reconcile_pending" | "pr_open" | "unresolved" | "blocked" | "stale" | "cancelled" | "interrupted" | "quarantined";
  readonly "version": number;
  readonly "outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed" | null;
  readonly "created_at": number;
  readonly "updated_at": number;
  readonly "cancellation_requested": boolean;
  readonly "data_source": "stored_controller_state";
};

export type CommandView = {
  readonly "step_id": string;
  readonly "kind": "foreground" | "start";
  readonly "argv": ReadonlyArray<string>;
  readonly "cwd": string;
  readonly "outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed";
  readonly "exit_code": number | null;
  readonly "stdout_tail": string;
  readonly "stderr_tail": string;
};

export type DecisionRequest = {
  readonly "request_id": string;
  readonly "expected_version": number;
  readonly "case_sha": string;
  readonly "action": "cancel" | "recheck";
};

export type DecisionResult = {
  readonly "action": "cancel" | "recheck";
  readonly "case": CaseSummary;
  readonly "replacement_case_id": string | null;
};

export type EventPage = {
  readonly "items": ReadonlyArray<EventView>;
  readonly "next_cursor": number | null;
};

export type EventView = {
  readonly "event_id": number;
  readonly "kind": string;
  readonly "phase": "queued" | "fetching" | "baseline_running" | "investigating" | "needs_input" | "proof_running" | "verified" | "repair_ready" | "publishing" | "reconcile_pending" | "pr_open" | "unresolved" | "blocked" | "stale" | "cancelled" | "interrupted" | "quarantined";
  readonly "summary": string;
  readonly "created_at": number;
};

export type NeedsInputView = {
  readonly "reason_code": "missing_secret" | "maintainer_choice" | "external_authority" | "ambiguous_repository_fact";
  readonly "affected_step_id": string | null;
  readonly "prompt": string;
  readonly "supported_actions": ReadonlyArray<"cancel" | "recheck">;
};

export type ProofView = {
  readonly "tested_sha": string;
  readonly "git_tree": string;
  readonly "outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed";
  readonly "verified": boolean;
  readonly "candidate_digest": string | null;
  readonly "candidate_tree_digest": string | null;
  readonly "content_tree_digest": string;
  readonly "target_digest": string;
  readonly "recipe_digest": string;
  readonly "readme_digest": string;
  readonly "verifier_digest": string;
  readonly "policy_digest": string;
  readonly "runtime_digest": string;
  readonly "runtime_image_id": string;
  readonly "fresh_state": boolean;
  readonly "cleanup_succeeded": boolean;
};

export type RecipeStepView = {
  readonly "id": string;
  readonly "kind": "foreground" | "start";
  readonly "argv": ReadonlyArray<string>;
  readonly "cwd": string;
  readonly "timeout_seconds": number;
};

export type RecipeView = {
  readonly "version": 1;
  readonly "steps": ReadonlyArray<RecipeStepView>;
};

export type RepositoryDetail = {
  readonly "repository": RepositorySummary;
  readonly "approved_sha": string;
  readonly "source_prefix": "" | "fixtures/notes-app";
  readonly "target": TargetView;
  readonly "recipe": RecipeView;
  readonly "setup_instructions": string;
  readonly "target_digest": string;
  readonly "recipe_digest": string;
  readonly "protected_digest": string;
  readonly "verifier_digest": string;
  readonly "policy_revision": string;
  readonly "policy_digest": string;
  readonly "runtime_digest": string;
  readonly "runtime_image_id": string;
};

export type RepositorySummary = {
  readonly "repository_id": number;
  readonly "owner": string;
  readonly "name": string;
  readonly "branch": string;
  readonly "current_head": string | null;
  readonly "latest_checked_sha": string | null;
  readonly "latest_outcome": "passed" | "failed" | "timed_out" | "infrastructure_error" | "policy_blocked" | "unsupported" | "cleanup_failed" | null;
  readonly "open_case_id": string | null;
  readonly "open_case_phase": "queued" | "fetching" | "baseline_running" | "investigating" | "needs_input" | "proof_running" | "verified" | "repair_ready" | "publishing" | "reconcile_pending" | "pr_open" | "unresolved" | "blocked" | "stale" | "cancelled" | "interrupted" | "quarantined" | null;
  readonly "automatic_prs": boolean;
  readonly "observed_at": number | null;
  readonly "data_source": "stored_controller_state";
};

export type SessionUserView = {
  readonly "id": number;
  readonly "login": string;
};

export type SessionView = {
  readonly "authenticated": boolean;
  readonly "configured": boolean;
  readonly "user": SessionUserView | null;
  readonly "csrf_token": string | null;
  readonly "can_write": boolean;
  readonly "reason": string | null;
};

export type StartRunRequest = {
  readonly "request_id": string;
};

export type TargetView = {
  readonly "runtime_image": string;
  readonly "platform": "linux/amd64" | "linux/arm64";
  readonly "network": "none";
  readonly "app_port": number;
  readonly "readiness_path": string;
  readonly "readiness_status": 200;
  readonly "readiness_timeout_seconds": number;
  readonly "verifier_id": string;
  readonly "acceptance_timeout_seconds": number;
};
